[package]
name = "crabdropper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
screenshots = "0.5.1"
image = "0.24.5"
termcolor = "1.2.0"
copypasta-ext = "0.4.1"
iced = "0.7.0"
iced_winit = "0.7.0"
iced_wgpu = "0.8.0"
